version: '3'
services:
  portfolio:
    container_name: portfolio
    image: 'syahrul12345/portfolio'
    build: ./src
    environment:
      - port=${port} 
      - is_production=true
    ports: 
      - ${port}:${port}